---
- name: Add stirling-pdf directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    state: directory

- name: Add stirling-pdf configs directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/configs"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    state: directory

- name: Add stirling-pdf customFiles directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/customFiles"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    state: directory

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: stirlingtools/stirling-pdf:latest
    pull: yes
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/configs:/configs"
      - "{{ docker_dir }}/{{ container_name }}/customFiles:/customFiles"
    ports:
      - "{{ stirling_pdf_port }}:8080"
    restart_policy: unless-stopped
    env:
      DOCKER_ENABLE_SECURITY: "false"
      SYSTEM_ROOTURIPATH: "/stirling-pdf"
      SECURITY_ENABLELOGIN: "false"